Controllers/KitchenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BreakfastWebAppV2.Data;
using BreakfastWebAppV2.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BreakfastWebAppV2.Controllers
{
    public class KitchenController : Controller
    {
        private ApplicationDbContext context;

        public IActionResult Index()
        {
            var rooms = context.Rooms.Include(r => r.Occupants).ToList();
            return View("Index", new KitchenViewModel(rooms, new DateTime(2020, 4, 19)));
        }

        [HttpPost]
        public ActionResult Submit()
        {
            var rooms = context.Rooms.Include(r => r.Occupants).ToList();
            return View("Index", new KitchenViewModel(rooms, DateTime.Parse(Request.Form["date"])));
        }

        public KitchenController(ApplicationDbContext dbcont)
        {
            context = dbcont;
        }
    }
}

Controllers/ReceptionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BreakfastWebAppV2.Data;
using BreakfastWebAppV2.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BreakfastWebAppV2.Controllers
{
    public class ReceptionController : Controller
    {
        private ApplicationDbContext context;

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Get()
        {
            var rooms = context.Rooms.Include(r => r.Occupants).ToList();
            return View(new ReceptionViewModel(rooms, new DateTime(2020, 4, 19)));
        }

        public IActionResult Set()
        {
            return View(new ReceptionViewModel(null, new DateTime(2020, 4, 19)));
        }

        [HttpPost]
        public ActionResult GetSubmit()
        {
            var rooms = context.Rooms.Include(r => r.Occupants).ToList();
            return View("Get", new ReceptionViewModel(rooms, DateTime.Parse(Request.Form["date"])));
        }

        [HttpPost]
        public async Task<IActionResult> Edit(DateTime date, int RoomNumber, int AdultsWantBreakfast, int ChildrenWantBreakfast)
        {


            if (RoomNumber < 0)
            {
                return NotFound();
            }

            var room = await context.Rooms
                .Where(r => r.RoomNumber == RoomNumber)
                .Where(c => c.Occupants.Any(i => i.Date == date))
                .Select(c => new
                {
                    c,
                    Occupants = c.Occupants.Where(i => i.Date == date)
                })
                .FirstOrDefaultAsync();

            if (room == null)
            {
                var room1 = await context.Rooms
                .Where(r => r.RoomNumber == RoomNumber)
                .Include(r => r.Occupants)
                .FirstOrDefaultAsync();

                room1.Occupants.Add(new Occupants
                {
                    Adult = AdultsWantBreakfast,
                    Children = ChildrenWantBreakfast,
                    Date = date
                });

            } 
            else
            {
                room.c.Occupants.First().Adult = AdultsWantBreakfast;
                room.c.Occupants.First().Children = ChildrenWantBreakfast;

                
            }

            context.SaveChanges();


            return View("Set", new ReceptionViewModel(null,date));
        }





        //public ActionResult SetSubmit()
        //{
        //    string date_string = Request.Form["date"];
        //    DateTime date = DateTime.Parse(date_string);
        //    string roomnumber_string = Request.Form["RoomNumber"];
        //    int roomnumber = int.Parse(roomnumber_string);
        //    string adultsbreakfast_string = Request.Form["AdultsWantBreakfast"];
        //    int adultsbreakfast = int.Parse(adultsbreakfast_string);
        //    string childrenbreakfast_string = Request.Form["ChildrenWantBreakfast"];
        //    int childrenbreakfast = int.Parse(childrenbreakfast_string);

        //    //List<Room> RoomToEdit = context.Rooms
        //    //    .Where(r => r.RoomNumber == roomnumber)
        //    //    .Include(r => r.Occupants)
        //    //    .ToList();


        //     var RoomToEdit = context.Rooms
        //        .Where(r => r.RoomNumber == roomnumber)
        //        .Where(c => c.Occupants.Any(i => i.Date == date))
        //        .Select(c => new
        //        {
        //            c,
        //            Occupants = c.Occupants.Where(i => i.Date == date)
        //        })
        //        .FirstOrDefault();

        //    //.Where(r => r.Occupants.Any(o => o.Date == date))

        //    if (RoomToEdit != null)
        //    {
        //        //RoomToEdit.Occupants[0].;
        //    }

            

        //    return View("Set");
        //}

        public ReceptionController (ApplicationDbContext dbcont)
        {
            context = dbcont;
        }
    }
}

Controllers/ResturantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using BreakfastWebAppV2.Data;
using BreakfastWebAppV2.Models;

namespace BreakfastWebAppV2.Controllers
{
    public class RestaurantController : Controller
    {
        public IActionResult Index(RestaurantViewModel model)
        {
            return View(model);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Hotel California</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" media="min-width: 480px" />
        <link rel="stylesheet" href="~/css/mobile.css" media="only screen and (max-width: 480px)" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" media="min-width: 480px" />
        <link rel="stylesheet" href="~/css/mobile.css" media="only screen and (max-width: 480px)" />
    </environment>
</head>
<body>
    <div class="container">
        <header>

            @*<img src="~/images/banner.png" class="d-none d-sm-block center-img" />*@

            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container">
                    @*<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/banner.png"/></a>*@
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <partial name="_LoginPartial" />
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            @if (User.HasClaim("Cook", "Yes"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Kitchen" asp-action="Index">Kitchen</a>
                                </li>
                            }
                            @if (User.HasClaim("Receptionist", "Yes"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Reception" asp-action="Get">Reception Get</a>
                                </li>
                                <li>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Reception" asp-action="Set">Reception Set</a>
                                </li>
                            }
                            @if (User.HasClaim("Waiter", "Yes"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Restaurant" asp-action="Index">Restaurant</a>
                                </li>
                            }
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
    </div>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            Copyright &copy; 2020 - Hotel California
            @*<br/><a href="mailto:HotelCalifornia@fakemail.com">HotelCalifornia@fakemail.com</a>*@
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    @RenderSection("Scripts", required: false)
</body>
</html>